version: '2.4'

services:
  web:
    build:
      context: ./src/
      target: dev
    volumes:
      - .:/src
    command: npm run start:dev
    ports:
      - "8000:8000"
    environment:
      NODE_ENV: development
      DEBUG: nodejs-docker-express:*